name: Compilar APK de Android

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Build con Buildozer Action
      uses: LorenzoMorelli/buildozer-action@v1
      with:
        buildozer_version: master
        command: buildozer android debug

    - name: Subir APK como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: TikTokBot-APK
        path: bin/*.apk
        
